##
## EPITECH PROJECT, 2025
## B-YEP-400-NAN-4-1-zappy-albane.merian
## File description:
## Audio Makefile
##

# ANSI Colors
GREEN=\033[1;32m
BLUE=\033[1;34m
RED=\033[1;31m
YELLOW=\033[1;33m
NC=\033[0m

all:
	@make -C ./SFML

clean:
	@make -C ./SFML clean


fclean: clean
	@make -C ./SFML fclean

re: fclean all

.PHONY: all clean fclean re
