##
## EPITECH PROJECT, 2023
## painauchocolat
## File description:
## Bonus
##

name: painauchocolat


on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"


env:
  EXECUTABLES: "zappy_server;zappy_gui;zappy_ai"

jobs:
  draw_doofenschmirtz:
    name: Secret Job ;)
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: CLICK HERE TO SEE "DOOF DOOF"
        run: |
          echo "::notice title=DOOFENSCHMIRTZ::CLICK HERE"
          echo "/\_/\
                (o.o)
                 >^<"


  check_program_compilation:
    name: Check Program Compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Compilation
        run: make
        timeout-minutes: 5

      - name: Clean
        run: make clean

      - name: Server
        run: make zappy_server

      - name: GUI
        run: make zappy_gui

      - name: AI
        run: make zappy_ai

  server_style:
    name: Check Any Coding Style Errors in C Files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Run Coding-Style-Checker
        run: check.sh $(pwd) $(pwd)

      - name: Check Any Error
        run: |
          cat coding-style-reports.log
          if [ -s coding-style-reports.log ]; then
            exit 1
          else
            exit 0
          fi

  coding_style_cpp:
    name: Check Coding Style CPP
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          apt update && apt install -y python3-pip
          pip install --break-system-packages cpplint
          chmod +x styleChecker.sh

      - name: Check Coding Style
        run: |
          ./styleChecker.sh

  coding_style_python:
    name: Check Coding Style Python
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          apt update && apt install -y python3-pip
          pip install --break-system-packages pycodestyle
          chmod +x pythonStyleChecker.sh

      - name: Check Python Coding Style
        run: |
          ./pythonStyleChecker.sh

      - name: Verify Python Coding Style
        run: |
          if [ -s coding-style-python-reports.log ]; then
            echo "Python coding style errors found. See coding-style-python-reports.log for details."
            cat coding-style-python-reports.log
            exit 1
          else
            echo "No Python coding style errors found."
          fi

  check_coding_style_c:
      name: Check Any Coding Style Errors in C Files
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/epitech/coding-style-checker:latest
      steps:
        - name: checkout@v4
          uses: actions/checkout@v4

        - name: Run Coding-Style-Checker
          run: |
            check.sh $(pwd) $(pwd) || { echo "check.sh failed"; exit 1; }
            if [ ! -s coding-style-reports.log ]; then
              echo "coding-style-reports.log is empty or missing."
              exit 0
            fi
            grep -v "./documentation" coding-style-reports.log > new-coding.log || true
            rm -f coding-style-reports.log

        - name: Check Any Error
          run: |
            if [ ! -s new-coding.log ]; then
              echo "No coding style errors found."
              exit 0
            fi
            cat new-coding.log | while read line; do
              TYPE=$(echo $line | cut -d ':' -f 3 | cut -c 2-)
              temp=$(echo $line | cut -d ':' -f 1)
              NAME=$(echo $temp | cut -d '/' -f 2)
              LINE=$(echo $line | cut -d ':' -f 2)
              NBR=$(echo $line | cut -d ':' -f 4)
              ERROR=$(printf "%s coding style error" "$TYPE")
              echo "::error file=$NAME,line=$LINE,title=$ERROR::$NBR"
            done
            exit 1


  run_functionnal_tests:
    name: Run Functional Tests
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Run functional tests
        run: |
          make functional_tests
          if [ $? -ne 0 ]; then
            echo "Functional tests failed"
            exit 1
          fi

  run_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout@v4
        uses: actions/checkout@v4

      - name: Install Google Test and Google Mock
        run: |
          apt-get update
          apt-get install -y libgtest-dev libgmock-dev cmake
          cd /usr/src/gtest
          cmake CMakeLists.txt
          make
          cp lib/*.a /usr/lib
          cd /usr/src/googletest/googlemock
          cmake CMakeLists.txt
          make
          cp lib/*.a /usr/lib
          cd -

      - name: Install pytest and dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip install --break-system-packages pytest pytest-cov

      - name: Run Unit Tests
        run: make tests_run
        timeout-minutes: 5
